# Generated by Django 5.2.6 on 2025-09-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
